### ISSUE TITLE
Specifying 'socksProxy' requires an integer for 'socksVersion'

### ISSUE THREAD

**Issue by Mecanik** [GermanAizek/webdriverxx#1]
Hello! I see (and hope) you plan to maintain this. I've create an issue on another fork but.. that guy doesn't care so there is no point to insist there.

I've take your fork and I see you have the same issue with the socks proxy, could you please add the following:

```
struct SocksProxy : ManualProxy { // copyable
	explicit SocksProxy(const std::string& address) { SetProxyAddress(address); }

	WEBDRIVERXX_PROPERTIES_BEGIN(SocksProxy)
	WEBDRIVERXX_PROPERTY(ProxyAddress, "socksProxy", std::string)
	WEBDRIVERXX_PROPERTY(Username, "socksUsername", std::string)
	WEBDRIVERXX_PROPERTY(Password, "socksPassword", std::string)
	**WEBDRIVERXX_PROPERTY(ProxyVersion, "socksVersion", int)**
	WEBDRIVERXX_PROPERTIES_END()
};
```

Then we can use: 

`SocksProxy("").SetProxyVersion(5)`

This problem appears with chrome driver.

```
org.openqa.selenium.InvalidArgumentException: invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: proxy
from invalid argument: Specifying 'socksProxy' requires an integer for 'socksVersion'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
```

However, afterwards I get the same crash.... https://prnt.sc/spe5bm

Could you give a hand ?

Thanks

**Comment by GermanAizek** [comment]
SOLUTION HERE:
https://github.com/GermanAizek/webdriverxx/issues/14#issuecomment-816971664
