### ISSUE TITLE
Can't open chrome as mobile

### ISSUE THREAD

**Issue by SrMilton** [GermanAizek/webdriverxx#10]
I've already tried using SetMobileEmulation and changing setplatform to android but nothing works. SetEmulation nothing happens (idk if i did something wrong) and SetPlataform Android web driver doesn't open.
Idk if it's a problem or if i'm just dumb enoght to don't realize how to use this version of selenium hahah.

Any ideas?

**Comment by GermanAizek** [comment]
@SrMilton thank you very much for the feedback.
At the moment, capability mobileEmulation is poorly described, I will add the necessary parameters for working with mobile emulation from the documentation of chromedriver today and add a list of ready-made device list as in google chrome.

**Comment by GermanAizek** [comment]
@SrMilton, I will not forget to make examples for easy understanding and gtests before building

**Comment by GermanAizek** [comment]
@SrMilton, You can see the changes here https://github.com/GermanAizek/webdriverxx/commit/5d94d4fac0334b0ee7a49b7fd2ad7e5eec279a34

**Comment by GermanAizek** [comment]
@SrMilton,
This fixed and supplemented, I am waiting for your response about testing new feature.

**Comment by SrMilton** [comment]
@GermanAizek Wow fast af hahah.
Btw, chrome still starting as PC mode.

Code:
`   chrome::MobileEmulation me;
    me.SetdeviceName(chrome::device::Get("Galaxy Note 3"));
    WebDriver gc = Start(Chrome().SetMobileEmulation(me));
    gc.Navigate("https://www.google.com.br/");
    `
    
Result:
![image](https://user-images.githubusercontent.com/35127424/111493088-01904c00-871c-11eb-9677-31e3703d493a.png)

What i'm doing wrong?

**Comment by GermanAizek** [comment]
Very strange behavior chromedriver it cast object JsonObject to double.

> The mobile_emulation capability was added to ChromeDriver in 2.11

Do you have a higher version?

**Comment by GermanAizek** [comment]
@SrMilton,
How the temporary solution should work directly jsonobject generation for chromedriver.
Try my option. I will edit this function definitively. When I'm done, I'll notify you.

`
JsonObject me;
me.Set("deviceName", "Galaxy Note 3");
auto cap = Capabilities().Set("mobileEmulation", me);
WebDriver gc = Start(Chrome(), cap);
gc.Navigate("https://www.google.com.br/");
`

**Comment by GermanAizek** [comment]
@SrMilton,
If you need  parameters for mobile emulation, the code below:

Google Nexus 5
```cpp
JsonObject dm;
dm.Set("width", 360);
dm.Set("height", 640);
dm.Set("pixelRatio", 3.0);
dm.Set("touch", true);

JsonObject me;
me.Set("userAgent", "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19");
me.Set("deviceMetrics", dm);

auto cap = Capabilities().Set("mobileEmulation", me);
WebDriver gc = Start(Chrome(), cap);
gc.Navigate("https://www.google.com.br/");
```

**Comment by SrMilton** [comment]
@GermanAizek I'm using the last stable version of ChromeDriver, "ChromeDriver 89.0.4389.23".

> ```c++
> JsonObject me;
> me.Set("deviceName", "Nexus 5");
> auto cap = Capabilities().Set("mobileEmulation", me);
> WebDriver gc = Start(Chrome(), cap);
> gc.Navigate("https://www.google.com.br/");
> ```

I was doing exaclty this before open this issue, but nothing happens, btw we can't use "Start(Chrome(), cap);" this way (at least for me doesn't work your method), the correct way is:

> ```c++
> JsonObject me;
> me.Set("deviceName", "Nexus 5");
> Capabilities cap; //Change here
> cap.Set("mobileEmulation", me); //And here
> WebDriver gc = Start(Chrome(), cap);
> gc.Navigate("https://www.google.com.br/");
> ```

But nevermind, still the same, look:
![image](https://user-images.githubusercontent.com/35127424/111557333-3aa3dd00-876b-11eb-8145-aac594326dd4.png)

And your last solution defining parameters don't work, absolutely nothing happens in Selenium, my program just open and close.

My configs:
Windows 10 64 bits
Google Chrome 89.0.4389.90 (Official version) 64 bits
ChromeDriver 89.0.4389.23 x32
Visual Studio 2019 (v142)
Windows SDK Version: 10.0.18362.0
MFC in a Static Library
Unicode Character Set
Compiling Release x64

If you have any solution just send to me and i'll test and give to you a feedback asap. Thanks!

**Comment by GermanAizek** [comment]
@SrMilton,
Have you tried the сommits to roll back?

**Comment by SrMilton** [comment]
@GermanAizek i've just rolled back to the version before your last update and still absolutely the same. This is the error i was talking about:
![image](https://user-images.githubusercontent.com/35127424/111559256-f0bcf600-876e-11eb-9d06-481b397c2255.png)

**Comment by GermanAizek** [comment]
@SrMilton,
Replace Capabilities with JsonObject.

**Comment by SrMilton** [comment]
@GermanAizek i hope this is what you meant
![image](https://user-images.githubusercontent.com/35127424/111560017-65446480-8770-11eb-8763-6df9abf405c7.png)

**Comment by GermanAizek** [comment]
@SrMilton ,
```cpp
const char* url = "http://localhost:4444/wd/hub/";

auto ff = Start(Firefox(), url);

// or
auto ff = Start(Firefox(), Capabilities() /* required */, url);
```

Did you try specifying the url to the selenium server?

**Comment by SrMilton** [comment]
@GermanAizek yes, and i use port 4445, i've changed the client.h to "const char *const kDefaultWebDriverUrl = "http://localhost:4445/wd/hub/";" and EVERYTHING works perfectly, i have more than 400 lines of code using webdriverxx and everything works fine, but i can't open chrome as mobile, this is the last thing i need to finish my project hahah.

**Comment by GermanAizek** [comment]
@SrMilton,
I understand you, but initially no api was added to webdriverxx to work with MobileEmulation in chrome.
For many browsers, Capabilities are not fully made, too many browsers and for some it is difficult to find documentation.
I'll help you as much as I can. 👍

**Comment by SrMilton** [comment]
@GermanAizek Thanks man! Let me ask you something: Are your browser opening as Mobile using those methods?
I really appreciate your help dude! btw sorry if i'm texting something wrong, english is not my major language hahaha.

**Comment by GermanAizek** [comment]
@SrMilton,
The methods should work, but I didn't check on Windows.

**Comment by SrMilton** [comment]
@GermanAizek I'm using AutoIt to press CTRL+SHIFT+I and CTRL+SHIFT+M to open mobile mode while you don't find a solution to this crazy bug hahah. ofc this is the worst way to do what i want, but its good for now

**Comment by GermanAizek** [comment]
@SrMilton, Sounds brilliant. Genius.

![](https://memepedia.ru/wp-content/uploads/2017/05/KHhcEzQy3xA-600x338.jpg)

**Comment by GermanAizek** [comment]
@SrMilton,
You could do without AutoIt, functions that I recently added you can call the mobile mode
`Element::KeyDown()`, `Element::KeyUp()`, `Element::SendKeys()`

**Comment by SrMilton** [comment]
@GermanAizek alright, i'll implement this, Thanks!!

Another question: How can i start chrome with some extesion? I know in java we can simple use ChromeOptions(), but idk how to do this in webdriverxx..

Code in java:
>```
>ChromeOptions options = new ChromeOptions();
>options.addArguments(“–load-extension=” + pathToExtension);
>driver = new ChromeDriver(options);
>```

**Comment by GermanAizek** [comment]
@SrMilton,
Everything is very simple.

Example:
```cpp
std::vector<std::string> extensions {"/path/to/extension0.crx", "/path/to/extension1.crx", "/path/to/extension2.crx"};
WebDriver ff = Start(Chrome().SetExtensions(extensions));
```

**Comment by SrMilton** [comment]
@GermanAizek guess what..

![image](https://user-images.githubusercontent.com/35127424/111796640-2107b000-88a7-11eb-90cb-688bac965062.png)

I've created the .crx of the extension and nothing happens. I need the extension with a specific config. What i'm doing wrong?

**Comment by GermanAizek** [comment]
@SrMilton,
Have you been able to solve the path problem?

**Comment by SrMilton** [comment]
@GermanAizek not yet, any ideas?

**Comment by GermanAizek** [comment]
@SrMilton,
There is an idea to edit so that the character does not change / to utf8 code

**Comment by SrMilton** [comment]
@GermanAizek this is exaclty what i'm trying to figure out..

**Comment by GermanAizek** [comment]
@SrMilton,
There is an idea to edit so that the character does not change / to utf8 code

**Comment by GermanAizek** [comment]
@SrMilton,
I got free time and figured out how to make a new function to convert from sequence to utf-8.
In 30 minutes, I'll commit a new feature for testing.

**Comment by GermanAizek** [comment]
@SrMilton,
Look at the commit to understand the algorithm. This should work.
https://github.com/GermanAizek/webdriverxx/commit/664ecba8a5dde30cf55045bd437226fd95aa131b

Example:
```cpp
#include "detail/to_string.h"

std::vector<std::string> extensions {
    detail::ToUtf8("/path/to/extension0.crx"),
    detail::ToUtf8("/path/to/extension1.crx"),
    detail::ToUtf8("/path/to/extension2.crx")
};

WebDriver ff = Start(Chrome().SetExtensions(extensions));
```

**Comment by SrMilton** [comment]
@GermanAizek I liked your idea, but not worked hahah.

>```
>i += 5;
>```

The program still writing the u002f, but this time your function worked and...
![image](https://user-images.githubusercontent.com/35127424/111832371-75bf2100-88cf-11eb-8397-f0336f248ac0.png)

Yes, the path is "C:\\extension.crx", and after your function we have "C:\u002fsion.crx" hahahhah

 Ps: We need to use \\ instead of / in your function.

**Comment by SrMilton** [comment]
@GermanAizek alright, i give up hahahahahh. The best i found is set the path to "C:\nextension.crx", selenium print the \n, then i renamed the extension name to nextension.crx, the output in selenium is perfect but this trick doesn't work.. So..We can create a chrome profile with the extension preseted, but how can i select a profile in webdriver, i know in java is possible with:
>```java
>options.addArguments(“user-data-dir=C:\\Selenium\\BrowserProfile”);
>```

**Comment by GermanAizek** [comment]
@SrMilton,
I understood the problem. Conversion of UTF-8 to Unicode occurs after JSON is generated using the api, because JSON is required UTF-8 at RFC8259.
Chromedriver began to accept arguments in Unicode. This problem is open, how to pass your string "C:\extens.crx" if the transmission method occurs using JSON.
Unless I am mistaken.

**Comment by GermanAizek** [comment]
@SrMilton,
You tried a popular way to replace `\` with `\\` ?

**Comment by GermanAizek** [comment]
@SrMilton,
Does changing `\` to `\\` not help?

**Comment by GermanAizek** [comment]
@SrMilton,
I tested on Linux and I have the result of such

Code:
```cpp
#include <webdriverxx.h>

using namespace webdriverxx;

int main()
{
	std::vector<std::string> extensions {
		"C:\\adblock.crx"
	};
	
	WebDriver ff = Start(Chrome().SetExtensions(extensions));
	
	getchar();

	return 0;
}
```

![Screenshot_2021-03-20_19-54-24](https://user-images.githubusercontent.com/21138600/111871808-13cced00-899d-11eb-8183-f960a781c847.png)

**Comment by GermanAizek** [comment]
@SrMilton,
The example shown in Java is very easy to create.

Example:
```cpp
WebDriver gc = Start(Chrome().SetArgs({"user-data-dir=C:\\Selenium\\BrowserProfile"}));
```

**Comment by GermanAizek** [comment]
> So..We can create a chrome profile with the extension preseted, but how can i select a profile in webdriver, i know in java is possible with:
> 
> > ```java
> > options.addArguments(“user-data-dir=C:\\Selenium\\BrowserProfile”);
> > ```

@SrMilton,
The example shown in Java is very easy to create.

Example:
```cpp
WebDriver gc = Start(Chrome().SetArgs({"user-data-dir=C:\\Selenium\\BrowserProfile"}));
```

**Comment by SrMilton** [comment]
> @SrMilton,
> Does changing `\` to `\\` not help?

Aru joking with me? hahaha :p Yes, this is the FIRST thing i did, when i do \ the output is c:\u002fextension.crx, when i do \\ the output is c:\\extension.crx. This is why i'm suffering with this

**Comment by SrMilton** [comment]
@GermanAizek omg man, what is going on?? Believe in me, this is the LAST thing i need to do to end this project hahahahahahha
The first one i used ``\\`` and the second one i used ``/``

![image](https://user-images.githubusercontent.com/35127424/111879969-8af78680-8987-11eb-8c2b-836f7aa63e60.png)

It's only can be something about configuration in visual studio.. any ideas? also Thanks for your help!

**Comment by SrMilton** [comment]
> @SrMilton,
> I understood the problem. Conversion of UTF-8 to Unicode occurs after JSON is generated using the api, because JSON is required UTF-8 at RFC8259.
> Chromedriver began to accept arguments in Unicode. This problem is open, how to pass your string "C:\extens.crx" if the transmission method occurs using JSON.
> Unless I am mistaken.

i've just saw this, i'll try to study this case to solve this problem.

**Comment by GermanAizek** [comment]
@SrMilton,

Under Visual Studio, you can choose between several options Multi-Bytes, Unicode, and a third.

You will find that property in the project properties box,
right click on your project in the "Solution Explorer", select "Properties" (at the bottom), in the option tree go to "general", you will something like:

![How to enable Unicode in C++?](https://i.stack.imgur.com/KDlWt.jpg)

Select Unicode, Apply and Close.
Now rebuild the project, and it will work.

See more docs:
https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/unicode-and-multibyte-character-set-mbcs-support?view=msvc-160&viewFallbackFrom=vs-2019

**Comment by SrMilton** [comment]
@GermanAizek I have bad new to you.. this was one of the first things i checked when i faced this bug..

**Comment by SrMilton** [comment]
@GermanAizek I'm implementing the API of the extension, i just need to get a value from the page. Using the DevTools i can use ``document.getElementsByClassName("test1").valueOf().item("").getAttribute("data-valuekey")`` this prints something like ``"aBCsScxdsf548dsas48df5d-"`` (this is what i want).

How can i get this response? I've already tried something like:
> ```c++
>auto title = gc.Eval<std::string>("return document.getElementsByClassName(\"test1\").valueOf().item(\"\").getAttribute(\"data - >valuekey\")");
>```

but it's prob wrong. Do u have any tip?

Ps: i didn't know the extension has an API, sorry hahahah. btw i know i'm asking too much to you and THANKS for answering.

**Comment by SrMilton** [comment]
I'm closing this issue because it's "solved". Feel free to open again if you want. I'm finishing the project rn, Thanks @GermanAizek .

**Comment by GermanAizek** [comment]
@SrMilton,
Hi, there's a way with extensions.
Instead of specifying base64 string, webdriver can decrypt it.
