### ISSUE TITLE
Click() prob not returning in mobile mode

### ISSUE THREAD

**Issue by SrMilton** [GermanAizek/webdriverxx#11]
Hi, me again :)

Yes, AutoIt was a good idea, BUT...... when chrome is in mobile mode, the click function freezes my program. Let me explain what i'm trying to do:
> ```c++
> gc.FindElement(ByXPath("/html/body/div[1]/section/main/div/header/div/div/div/button")).Click();
> ```
and it works perfectly in normal mode, it clicks and the program still running as normal, but when i try to do the exact same thing in chrome mobile mode, the click WORKS, but the program stops, it's not crashing or stop responding, it's just still waiting the function return successful like an infinity Sleep.

What should i do?

**Comment by GermanAizek** [comment]
@SrMilton, thx for feedback.
You tried after entrance mobile mode to return to normal and only then click?

**Comment by GermanAizek** [comment]
@SrMilton,
Do you enter mobile mode before loading the page using Navigate()?

**Comment by SrMilton** [comment]
@GermanAizek 
> You tried after entrance mobile mode to return to normal and only then click?

I've just spent 3-4 hours trying to fix it and your "solution" worked
![image](https://user-images.githubusercontent.com/35127424/111709056-b6faf680-8825-11eb-8b73-80b4179f8902.png)

Btw there are some way to verify if a Element exists? Something like:
>```c++
>Element button = gc.FindElement(ByXPath("/html/body/div[3]/div/div/div/div[3]/button[2]"));
>if(button){
>button.Click();
>}
```

Invalid clicks will crash the program :/

**Comment by GermanAizek** [comment]
@SrMilton,
You can check for the existence of an element using `IsDisplayed()`
But syntactically correct, you said it's more convenient to just check the object itself. Maybe I will append in milestones as feature.

Example:
```cpp
auto element = driver.FindElement(ByName("async_element"));
if (element.IsDisplayed())
    element.Click();
```

**Comment by SrMilton** [comment]
@GermanAizek 

For some reason still crashing
>```c++
>auto element = gc.FindElement(ByXPath("/html/body/div[3]/div/div/div/div[3]/button[2]"));
>        if (element.IsEnabled() && element.IsDisplayed())
>        {
>            element.Click();
>        }
>        element = gc.FindElement(ByXPath("/html/body/div[4]/div/div/div/div[3]/button[2]"));
>        if (element.IsEnabled() && element.IsDisplayed())
>        {
>            element.Click();
>        }
>```

The first check looks normal, because it's a true situation, but the second check i know it's false, but the program crash when try to GetElement. I have to do this because this script will loop 3 times, 1° time only the 1° button appers(so i need the 1° GetElement verify), 2° time only the 2° button appers, and the 3° time there are no buttons.

I hope you undestand, what should i do?

**Comment by GermanAizek** [comment]
@SrMilton,
Используйте функцию `Element::GetRef()` для проверки сходства двух элементов. `GetRef()` возвращает `std::string`, show element references.

**Comment by GermanAizek** [comment]
@SrMilton,
You were able to deal with the click on two elements, did the function `Element::GetRef()` help?
Can I close the issue?

**Comment by SrMilton** [comment]
@GermanAizek not yet, but we can close this issue and if the GetRef not work, i open a new one with the correct title.
