### ISSUE TITLE
gc.GetCookies();

### ISSUE THREAD

**Issue by SrMilton** [GermanAizek/webdriverxx#12]
Hi @GermanAizek , me again, this is the last time I promise hahahah.

This is not a issue at all. I have to get the page cookies and then "convert" it to a string to send in a Link (using curl) to an API.

How can i do that? 

>```
>auto cookies = gc.GetCookies();
>```

URL Format:
```
Format: KEY:Value, separator: semicolon, example: KEY1:Value1;KEY2:Value2;
```

btw if you have Discord, please send to me. I really enjoyed this project but has a lot of things which i got confused hahahah. also the program is finished, but the API requests the page's cookies, so...

**Comment by GermanAizek** [comment]
@SrMilton,
r2_allow_r1_lights #1080

**Comment by GermanAizek** [comment]
@SrMilton,

This is very ez.
Full working code.
```cpp
#include <webdriverxx.h>
#include <iostream>
#include <sstream>

using namespace webdriverxx;

int main()
{	
	WebDriver gc = Start(Chrome());
	gc.Navigate("https://alexanderbrandon.bandcamp.com/");
	
	std::stringstream format_result;
	for (auto p : gc.GetCookies()) {
		format_result << p.name << ':' << p.value << ';';
	}
	
	std::cout << format_result.str();
	
	getchar();

	return 0;
}
```

**Comment by GermanAizek** [comment]
@SrMilton,
Have you solved your problem?

**Comment by SrMilton** [comment]
@GermanAizek Your message waked me up today hahaha, here it was 5:55 AM zzzz. I'm having other problems rn but the cookies seems ok
