### ISSUE TITLE
Proxy still not working (Windows)

### ISSUE THREAD

**Issue by SrMilton** [GermanAizek/webdriverxx#16]
I have no words to this

>```c++
>WebDriver gc = Start(Chrome().SetProxy(
>        SocksProxy("127.0.0.25:9000")));
>```

![image](https://user-images.githubusercontent.com/35127424/115054927-34fafd80-9eb7-11eb-8c96-055e2a3b7bbd.png)

Windows 10
Selenium Server 4.0.0 beta 2

Edit: same with firefox

**Comment by GermanAizek** [comment]
![](https://www.meme-arsenal.com/memes/9a26b52835fbaef2d15322afe47138ee.jpg)

**Comment by GermanAizek** [comment]
@SrMilton,
Pls check with new patch #17
