### ISSUE TITLE
Need Help to create headlessly Firefox for server

### ISSUE THREAD

**Issue by nitinrakhpune** [GermanAizek/webdriverxx#19]
Hi,
    How can I run Firefox on Linux server heedlessly any option for this in here

**Comment by GermanAizek** [comment]
![](https://i.pinimg.com/originals/2b/98/a2/2b98a2772170108e1afbaf0cf0184a5f.jpg)

**Comment by GermanAizek** [comment]
@nitinrakhpune,
Thx for the feedback.
Added `moz:firefoxOptions` and slightly refactored code, now you can add arguments in browser session.
Reference: https://github.com/GermanAizek/webdriverxx/commit/b85a2cb1ed608eb48b0acf5032999a7737367c00

Please before using example, clone repo with latest changes.

Example:
```js
FirefoxOptions opts;
opts.SetFirefoxArgs({"--headless"});
WebDriver ff = Start(Firefox().SetFirefoxOptions(opts));
ff.Get("https://nyanpasu.com");
```

**Comment by GermanAizek** [comment]
@nitinrakhpune,
Please note I updated the syntax for Firefox capabilities.
Reference: https://github.com/GermanAizek/webdriverxx/commit/a39597b653afc5fc648168e7f5347dec76b3490f#diff-27c7f224e283858603465fb43e88c3380acc9807eaf5054b3229343c22c498ed

**Comment by nitinrakhpune** [comment]
Hi
   Thanks for your valuable support , I would like to contribute to this
framework.


Thanks
Nitin

**Comment by GermanAizek** [comment]
@nitinrakhpune,
Okay, just stick to our code style. Create pull requests and I review it.
I was surprised I helped you so quickly.

![](https://i.ytimg.com/vi/D3wEwchBS9s/hqdefault.jpg)

**Comment by GermanAizek** [comment]
@nitinrakhpune,
We can organize a party in any social network or messenger, it is preferable to raise our IRC or XMPP server. You can also fully deploy a bagtracker with full documentation on the site.

**Comment by nitinrakhpune** [comment]
Hi

   Sure, will do that.

Thanks
nitin
