### ISSUE TITLE
Compilation Warning: multi-character character constant

### ISSUE THREAD

**Issue by zzxx-husky** [GermanAizek/webdriverxx#22]
When I compile webdriverxx, the compilers complains the following:

```
./include/webdriverxx/webdriverxx/detail/to_string.h:120:21: warning: multi-character character constant [-Wmultichar]
    result.push_back('//');
```

https://github.com/GermanAizek/webdriverxx/blob/fcd20c42941105cf7122f8e94ed0fbd72c484dff/src/include/webdriverxx/detail/to_string.h#L120

Is that really a typo in the code?

**Comment by GermanAizek** [comment]
@zzxx-husky,
Thanks for noticing the warning, this feature can be removed because it is no longer in use.
