### ISSUE TITLE
Session ID is not a string

### ISSUE THREAD

**Issue by senko1337** [GermanAizek/webdriverxx#23]
When i start new session i have this issue
![image](https://user-images.githubusercontent.com/59355976/138129090-659c9f30-04c7-45e1-ad70-db91b2ba39e1.png)
помогите блин(

**Comment by senko1337** [comment]
> @senko1337 Tell me more about what you did and put out some code that causes an exception or compilation error. If session id is not a string, try to change the type to int, but according to the documentation it was previously a string.

im using code from example on windows
`WebDriver gc = Start(Chrome());`
Using picojson from https://github.com/kazuho/picojson
and curl library from https://github.com/curl/curl (without openssl)

Im trying to check quietExceptions but it returns an exception too
![image](https://user-images.githubusercontent.com/59355976/138221245-bc3a9afc-89bd-4479-89fd-4f1c6391b052.png)

maybe
`	
const auto response = resource_->Post("session",
		JsonObject()
			.Set("desiredCapabilities", static_cast<picojson::value>(desired))
			.Set("requiredCapabilities", static_cast<picojson::value>(required))
			);`
returns an erroneous value

**Comment by GermanAizek** [comment]
@senko1337 
hey, try replacing constant string "session" with "newSession"

https://github.com/GermanAizek/webdriverxx/blob/51225addabe7d4f76827ca5c3954ebc4fedb96ee/src/include/webdriverxx/client.inl#L49-L53

**Comment by GermanAizek** [comment]
![image](https://i.imgur.com/j0bkO2S.png)
