### ISSUE TITLE
Cant start Chrome Windows 10.

### ISSUE THREAD

**Issue by amrkamal2025** [GermanAizek/webdriverxx#24]
Hi,
Thank you for this great library it works perfect for FireFox, but I can't start Chrome browser not sure what I do wrong, or what I am missing to make it work, this is the issue after I run the chrome and the app crash, this log from server.

```
Starting ChromeDriver 96.0.4664.45 (76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}) on port 64006
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
17:23:28.050 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "0da57dbfd02a5922a920f400f57f0715","eventTime": 1638113007529897201,"eventName": "exception","attributes": {"driver.url": "http:\u002f\u002flocalhost:64006","exception.message": "Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid\nfrom invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nBuild info: version: '4.1.0', revision: '87802e897b'\nSystem info: host: 'DESKTOP-8QSC5AU', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_311'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid\nfrom invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nBuild info: version: '4.1.0', revision: '87802e897b'\nSystem info: host: 'DESKTOP-8QSC5AU', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_311'\nDriver info: driver.version: unknown\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:131)\r\n\tat org.openqa.selenium.grid.node.config.DriverServiceSessionFactory.apply(DriverServiceSessionFactory.java:65)\r\n\tat org.openqa.selenium.grid.node.local.SessionSlot.apply(SessionSlot.java:143)\r\n\tat org.openqa.selenium.grid.node.local.LocalNode.newSession(LocalNode.java:314)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.startSession(LocalDistributor.java:513)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor.newSession(LocalDistributor.java:440)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.handleNewSessionRequest(LocalDistributor.java:648)\r\n\tat org.openqa.selenium.grid.distributor.local.LocalDistributor$NewSessionRunnable.lambda$run$1(LocalDistributor.java:612)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\r\n\tat java.lang.Thread.run(Unknown Source)\r\n","exception.type": "org.openqa.selenium.SessionNotCreatedException","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","session.capabilities": "{\"proxy\": {\"proxyType\": \"DIRECT\"},\"browserVersion\": \"\",\"browserName\": \"chrome\",\"platformName\": \"ANY\"}\n"}}

17:23:28.055 WARN [SeleniumSpanExporter$1.lambda$export$0] - {"traceId": "0da57dbfd02a5922a920f400f57f0715","eventTime": 1638113008055032800,"eventName": "HTTP request execution complete","attributes": {"http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue","http.host": "localhost:4444","http.method": "POST","http.request_content_length": "146","http.scheme": "HTTP","http.status_code": 500,"http.target": "\u002fsession"}}
```
what I tried is to add this line

```
    common.SetProxy(DirectConnection());
    //WebDriver driver = Start(Firefox(common), "http://localhost:1234");
    common.SetVersion("96");
    WebDriver driver = Start(Chrome(common), "http://localhost:4444");
```
but also not working, so any idea what this happen, and last thing, do you consider adding it on Conan.io package manager? it will be very cool, so far I connect CURL and gTest using Conan and use the headers directly, so you can easily get the rest of the packages needed on Conan link them.

Thank you in advance.

**Comment by Misus-Misty** [comment]
Pleas help me @amrkamal2025 how to setup and make selenium work with cpp on my desktop ;-; (any webbrowser is fine by me)
Thank you

**Comment by Mecanik** [comment]
> 

Did you even bother to read what it says....? "cannot parse capability: browserVersion"...

`common.SetVersion("96.0.4664.45");`

**Comment by GermanAizek** [comment]
> > 
> 
> Did you even bother to read what it says....? "cannot parse capability: browserVersion"...
> 
> `common.SetVersion("96.0.4664.45");`

@Mecanik,
To simplify API usage, I will create a constructor with a default value in spare time, but what is the default value?

**Comment by Mecanik** [comment]
> > > 
> > 
> > 
> > Did you even bother to read what it says....? "cannot parse capability: browserVersion"...
> > `common.SetVersion("96.0.4664.45");`
> 
> @Mecanik, To simplify API usage, I will create a constructor with a default value in spare time, but what is the default value?

If you do that, it won't help anything. These noobs do not read anything, they just wanna "copy/pasta" and use. Also, Chrome version changes too often to have a default value... so I suggest just leave it as is, and let them learn to read.

**Comment by GermanAizek** [comment]
Closing this issue due to poor reading of code documentation and tools.

**Comment by iDevTJ** [comment]
@amrkamal2025 
@Mecanik 
@GermanAizek 


Hi guys, I got the same issue and i was able to solve it by going to the declaration of struct "Chrome" and remove 

`SetVersion("")`


Next you can successfully launch the chromedriver:

`
#include <iostream>
#include <curl/curl.h>
#include <webdriverxx/webdriver.h>
#include <webdriverxx/browsers/chrome.h>

using namespace webdriverxx;

int main()
{
	// browser options
	Capabilities common;
	Chrome ch(common);
	ChromeOptions options;
	options.SetArgs({ "start-maximized", "user-data-dir=CUSTM_PATH_HERE" });
	ch.SetChromeOptions(options);

	// launch browser
	WebDriver driver = Start(ch);
	Session session = driver.Navigate('https://google.com');

	return 0;
}

`

**Comment by iDevTJ** [comment]
@amrkamal2025 
@Mecanik 
@GermanAizek 


Hi guys, I got the same issue and i was able to solve it by going to the declaration of struct "Chrome" and remove 

`SetVersion("")`


Next you can successfully launch the chromedriver:

```
#include <iostream>
#include <curl/curl.h>
#include <webdriverxx/webdriver.h>
#include <webdriverxx/browsers/chrome.h>

using namespace webdriverxx;

int main()
{
	// browser options
	Capabilities common;
	Chrome ch(common);
	ChromeOptions options;
	options.SetArgs({ "start-maximized", "user-data-dir=CUSTM_PATH_HERE" });  // optional
	ch.SetChromeOptions(options);

	// launch browser
	WebDriver driver = Start(ch);
	Session session = driver.Navigate('https://google.com');

	return 0;
}
```

**Comment by GermanAizek** [comment]
@iDevTJ,
Okay, I made a mistake. Empty version param should not be passed.

https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.desired_capabilities.html?highlight=version

https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by GermanAizek** [comment]
Issue closed due to fix commit https://github.com/GermanAizek/webdriverxx/commit/0b04c449b6f187ecff67addaf1a22ae23a43afd9
