### ISSUE TITLE
Adding CDP support

### ISSUE THREAD

**Issue by Mecanik** [GermanAizek/webdriverxx#26]
Hi,

I`m trying to add CDP commands support, but for some reason it fails at the moment.

`org.openqa.selenium.UnsupportedCommandException: POST /session/9fa9bcf54a4a09035beee36c1eb1c6b6/goog/cdp/execute`

- Selenium: 4.1.1
- Chrome: 97.0.4692.71
- Chrome Driver:  97.0.4692.71

Command code:

**session.inl**

```
inline
void Session::ExecuteCdpCommand(const std::string& commandName, const JsonObject& args) const {
	
	resource_->Post("goog/cdp/execute",
		JsonObject()
			.Set("cmd", commandName)
			.Set("params", args)
		);
}
```

Please advise if you know how to make this work, CDP support would be amazing!

**Comment by GermanAizek** [comment]
@Mecanik, new commit https://github.com/GermanAizek/webdriverxx/commit/e82470f00658686c378efeebe8f9224ec28b4831 
Please check it.

**Comment by Mecanik** [comment]
> @Mecanik, new commit [e82470f](https://github.com/GermanAizek/webdriverxx/commit/e82470f00658686c378efeebe8f9224ec28b4831) Please check it.

Thanks, does this work for you? Because I keep getting "org.openqa.selenium.UnsupportedCommandException", no matter what version of Selenium I use from 4.x, Google, Firefox or driver.

Could you make a test please?

**Comment by Mecanik** [comment]
I tried to manually POST as well, but it returns some weird error:

```
{
"value": {
"error": "unknown error",
"message": "null value in entry: message=null",
"stacktrace": "java.lang.NullPointerException: null value in entry: message=null at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:171) at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:137) at org.openqa.selenium.remote.ErrorCodec.encode(ErrorCodec.java:107) at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:50) at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64) at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44) at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:64) at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44) at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) "
}
}
```

**Comment by GermanAizek** [comment]
@Mecanik, try it.
Replace
`goog/cdp/execute -> -webkit-/cdp/execute `
or
`goog/cdp/execute -> -blink-/cdp/execute `

**Comment by GermanAizek** [comment]
@Mecanik, ok ur code correct.



I found in the java source for selenium the google chrome vendor prefix which is expect by the webdriver it is:

```java
  @Override
  public Map<String, CommandInfo> getAdditionalCommands() {
    return ImmutableMap.of(
      EXECUTE_CDP, new CommandInfo("session/:sessionId/goog/cdp/execute", HttpMethod.POST));
  }
```

**Comment by GermanAizek** [comment]
@Mecanik check it.
https://github.com/SeleniumHQ/selenium/issues/8672
and
https://stackoverflow.com/questions/47297877/to-set-mutationobserver-how-to-inject-javascript-before-page-loading-using-sele/47298910#47298910

**Comment by GermanAizek** [comment]
@Mecanik, try it.
```cpp
inline
picojson::value Session::ExecuteCdpCommand(const std::string& commandName, const JsonObject& args) const {
	return resource_->Post("chromium/send_command_and_get_result",
		JsonObject()
			.Set("cmd", commandName)
			.Set("params", args)
		);
}
```

or try replace `chromium -> goog`

**Comment by Mecanik** [comment]
Checking the source of Selenium, Chrome and Chrome Driver they all have this implemented. So maybe we are sending the body wrong or something.

**Comment by Mecanik** [comment]
I event tested Chromium instead of Chrome and tried "/chromium/send_command_and_get_result" but same...

**Comment by Mecanik** [comment]
Well, it seems a bit of a dead end. Apparently you must to WS request to Selenium.

**Comment by GermanAizek** [comment]
@Mecanik,
I will try to send the request, but first I will check the POST request difference headers and body between Python Webdriver and Webdriverxx.

**Comment by Mecanik** [comment]
> @Mecanik, I will try to send the request, but first I will check POST request headers and body difference between Python Webdriver and Webdriverxx.

Sure, you can also checkout my thread here: https://stackoverflow.com/questions/70654898/selenium-4-x-trying-to-post-cdp-unsupportedcommandexception - might give you some ideas.

**Comment by GermanAizek** [comment]
@Mecanik,
https://stackoverflow.com/questions/70654898/selenium-4-x-trying-to-post-cdp-unsupportedcommandexception#answer-70658001
In theory, you can make HACK through Selenium Grid and try it works or not

**Comment by GermanAizek** [comment]
@Mecanik,
Without api just commands in cmd, bash, powershell with chromedriver is working?

**Comment by Mecanik** [comment]
> @Mecanik, Without api just commands in cmd, bash, powershell and curl with chromedriver is working?

Correct, without selenium running chromedriver and doing your stuff works fine. Thanks for the link, I will have a look.

**Comment by Mecanik** [comment]
The problem is Selenium returns se:cdp via ws:// instead of http://, and I`m yet to figure out how to change that.

**Comment by GermanAizek** [comment]
@Mecanik,
I think it's worth comparing POST request bodies to goog/cdp/execute and python selenium
Print more info from `HttpResponse` object and compare them
https://github.com/GermanAizek/webdriverxx/blob/100861f75fdaaac3fd48e9a332385454567b447e/src/include/webdriverxx/detail/http_request.h#L49-L74

**Comment by GermanAizek** [comment]
> The problem is Selenium returns se:cdp via ws:// instead of http://, and I`m yet to figure out how to change that.

Is this from version 4?

**Comment by Mecanik** [comment]
> > The problem is Selenium returns se:cdp via ws:// instead of http://, and I`m yet to figure out how to change that.
> 
> Is this from version 4?

Yes, any version above 4. I tested like... all day.

**Comment by GermanAizek** [comment]
@Mecanik,
libcurl can work with websockets
Need to rewrite methods that work through `ws://`
There, the result itself returns through `ws://` or request?

https://stackoverflow.com/questions/47860689/how-to-read-websocket-response-in-linux-shell

https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0

https://stackoverflow.com/questions/64283588/c-getting-websocket-header-fields-using-libcurl

**Comment by Mecanik** [comment]
> @Mecanik, libcurl can work with websockets Need to rewrite methods that work through `ws://` There, the result itself returns through `ws://` or request?
> 
> https://stackoverflow.com/questions/47860689/how-to-read-websocket-response-in-linux-shell
> 
> https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0
> 
> https://stackoverflow.com/questions/64283588/c-getting-websocket-header-fields-using-libcurl

I never used WS with CURL so far, so it's interesting. With ws://, the result should be returned via ws://, since you become a "client" of the ws:// server.

**Comment by Mecanik** [comment]
Would be easier to just make Selenium return http:// endpoint properly, but I`m not a big fan of Java so looking into the sources takes ages.

https://github.com/SeleniumHQ/selenium/blob/e6366da0161af746ab1d449838ba280b6cfd7854/java/src/org/openqa/selenium/chrome/AddHasCdp.java#L34

https://github.com/SeleniumHQ/selenium/blob/45b62fcb18965e4a608be7c25251f731ef90e1e0/java/src/org/openqa/selenium/chrome/ChromeDriver.java#L108

**Comment by Mecanik** [comment]
@GermanAizek After many discussions, tests... and more tests with other people, it seems the current capabillities are sent in Selenium 3.x format and not 4.x. As such, please edit the following:

```
inline
Session Client::CreateSession(
	const Capabilities& desired,
	const Capabilities& required
	) const {
	WEBDRIVERXX_FUNCTION_CONTEXT_BEGIN()

	picojson::array capabilities;
	capabilities.push_back(picojson::value(desired));

	picojson::object firstMatch;
	firstMatch.insert(std::make_pair("firstMatch", picojson::value(capabilities)));

	const auto response = resource_->Post("session",
		JsonObject()
			//.Set("desiredCapabilities", firstMatch) // don't set this, for some reason it will fuck up.
			.Set("capabilities", firstMatch)
			.Set("requiredCapabilities", firstMatch)
		);

	const auto sessionId = response.get("value").get("sessionId");

	WEBDRIVERXX_CHECK(sessionId.is<std::string>(),                  "Session ID is not a string");
	WEBDRIVERXX_CHECK(response.get("value").is<picojson::object>(), "Capabilities is not an object");
	
	return MakeSession(sessionId.to_str(), detail::Resource::IsOwner);
	WEBDRIVERXX_FUNCTION_CONTEXT_END()
}
```

Notice the sub key firstMatch. This emulates what Selenium client sends, and after this you can use POST to send CDP commands.

```
inline
picojson::value Session::ExecuteCdpCommand(const std::string& commandName, const JsonObject& args) const {
	return resource_->Post("goog/cdp/execute",
		JsonObject()
		.Set("cmd", commandName)
		.Set("params", args)
	);
}
```

Notice "goog/cdp/execute".

**Comment by Mecanik** [comment]
Please note that if running with the above settings, W3C mode will be active. 

Which means if you want to execute scripts, the commands must be:

- /session/{session id}/execute/sync
- /session/{session id}/execute/async

**Comment by Mecanik** [comment]
Additions to support W3C style for text input on elements:

**keyboard.h**

```
	inline
		const Keyboard& SendInput(const std::string& input) const {
		resource_->Post(command_, JsonObject()
			.Set("text", input));
		return *this;
	}
```
**element.h**

`const Element& SendInput(const std::string& input) const;`

**element.inl**

```
inline
const Element& Element::SendInput(const std::string& input) const {
	GetKeyboard().SendInput(input);
	return *this;
}
```

**Comment by GermanAizek** [comment]
@Mecanik,
Thank you so much for your help, when the time is, I will make changes and you to Readme.md

**Comment by GermanAizek** [comment]
@Mecanik,
Sorry for the delay, was busy and tested your functionality on different chromedriver and selenium standalone, I put you in contributers with signed-off commit and in README.md
Commit is here: https://github.com/GermanAizek/webdriverxx/commit/aa61ee78e280f7312f0a980d1be52b2e2d65ffa9
Thank you very much for your huge contribution to fixing bugs.
