### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by Su5eD** [GermanAizek/webdriverxx#9]
I've been trying to do a clean compile on Debian (WSL), but it failed. 
- [x] I have all dependencies installed
### Steps to reproduce
1. Checkout the repository: `git clone https://github.com/GermanAizek/webdriverxx.git`
2. `mkdir build && cd build`
3. `cmake ../src`
4. `make`, results in an error: https://pastebin.com/CVneiQWG

### System details
- OS: Debian 9 (WSL)
- Compiler: gcc 6.3.0
- Cmake 3.7.2
- Make 4.1

**Comment by GermanAizek** [comment]
@Su5eD, thanks for the problem you found.
I will try to build a project in your proposed Debian WSL environment.

**Comment by GermanAizek** [comment]
Fixed the specified build error in the commit.
https://github.com/GermanAizek/webdriverxx/commit/70cdc37abe736c5a8e8a29a1aea16e162b62411d

**Comment by GermanAizek** [comment]
@Su5eD,
Let me know when you will successfully build the project.

**Comment by Su5eD** [comment]
I was able to build it successfully. Thanks
